name: Terraform CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  validate-networking:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/ia-lab-basic

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false