name: Terraform CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  validate-networking:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/ia-lab-basic

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Cache TFLint plugins
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
                    
      - name: Show Terraform version
        run: terraform version

      - name: Check Terraform formatting
        run: terraform fmt -check -diff -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Show TFLint version
        run: tflint --version

      - name: Initialize TFLint plugins
        run: tflint --init

      - name: Run TFLint
        run: tflint